name: task_manager_krainet
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.3.0+1 # app routing
  flutter_svg: ^2.0.17 # for svg icons
  provider: ^6.1.2 # # used to push data down the widget tree
  flutter_bloc: ^9.0.0 # general state manager in app
  # firebase services
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  equatable: ^2.0.7 # for comparison of custom classes
  get_it: ^8.0.3 # service locator for dependency injection
  # just for get_it package
  dio: ^5.4.3+1
  retrofit: ^4.4.2
  # database (local storage)
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  # json serialization
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  # id generator
  uuid: ^4.5.1
  # multi language/time support
  flutter_localizations:
    sdk: flutter
  intl: any
  timezone: ^0.10.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.0+1
  build_runner:
  # Mocking library for unit tests
  mockito: ^5.4.4
  # For widget testing with golden image testing
  golden_toolkit: ^0.15.0
  # For integration testing
  integration_test:
    sdk: flutter
  # For BLoC testing
  bloc_test: ^10.0.0
  # Network request mocking
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: ALSPofo
      fonts:
        - asset: assets/fonts/ALSPofo-Regular.ttf
        - asset: assets/fonts/ALSPofo-Light.ttf
          weight: 300
        - asset: assets/fonts/ALSPofo-Bold.ttf
          weight: 700

  assets:
    - assets/icons/
    - assets/fonts/
