// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdZRSuMxTUwvRZPRpZTcjTEwKUzajaWvM',
    appId: '1:317929820537:web:b2fcd153a53d604a0f1fa8',
    messagingSenderId: '317929820537',
    projectId: 'task-manager-krainet',
    authDomain: 'task-manager-krainet.firebaseapp.com',
    storageBucket: 'task-manager-krainet.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg4Ujv7V0TCs-qJ7rGPZtufo9495Zh790',
    appId: '1:317929820537:android:bf88caf1582e84420f1fa8',
    messagingSenderId: '317929820537',
    projectId: 'task-manager-krainet',
    storageBucket: 'task-manager-krainet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoOM-1hW9C_wrxupzTpEsJaqo8b7_6bXE',
    appId: '1:317929820537:ios:4c0d023c598c93160f1fa8',
    messagingSenderId: '317929820537',
    projectId: 'task-manager-krainet',
    storageBucket: 'task-manager-krainet.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerKrainet',
  );
}
